### PR TITLE
giving option to show table footnotes on every page

### PR DESCRIPTION
**Pull request by bd-karen-byron**
This resolves issue [#858](https://github.com/haozhu233/kableExtra/issues/858) show footnotes every page (with partial solution)

Added argument `show_every_page` to `footnote()`.  
If `show_every_page = TRUE` then table footnotes will show at the bottom of all pages for longtable pdf's.  
Code works for all permutations of `booktabs = T`/`F`, `three_part_table = T`/`F`, `latex_options = "basic"`/`"repeat_header"`, and `repeat_header_continued = T`/`F`. 
Includes exhaustive testing.

Feedback welcome.

### CODE REVIEW

**Comment by dmurdoch** [comment]
Looking at your changes, I see some changes to Rd files that don't appear to be related to your PR.  I'm guessing ROxygen made these.  Could you leave them out of the PR?  Maybe another one should be submitted, but I think we can count on it happening before the next release.

**Comment by bd-karen-byron** [comment]
submitted new pull
thanks

**Comment by dmurdoch** [comment]
Just came across an example that looks wrong to me:
````
---
title: "Untitled"
date: "2025-03-12"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(kableExtra)
latex <- kbl(head(mtcars), format="latex", longtable = TRUE, caption = "The caption")
footnote(latex, general = "General comment", show_every_page = TRUE)
```
````

This produces a funny label for the footnote, containing braces that I think weren't supposed to be escaped, so it looks like this: 
```
{ Note: }
General comment
```

**Comment by bd-karen-byron** [comment]
can reproduce your finding; will look into it

**Comment by bd-karen-byron** [comment]
have version robust to latex formatting, will make new pull

**Pull request closed without merging**
