### PR TITLE
Fixes for several issues

### PR DESCRIPTION
**Pull request by vincentarelbundock**

### CODE REVIEW

**Comment by vincentarelbundock** [comment]
I will not be able to work on this more in the near future, so I think this is ready for review->fixups->merge process.

Here are the issues resolved:

Install the branch with:

```r
remotes::install_github("vincentarelbundock/kableExtra@dev")
```


Pull Requests reviewed and merged into the `dev` branch:

* https://github.com/haozhu233/kableExtra/pull/749
* https://github.com/haozhu233/kableExtra/pull/686
* https://github.com/haozhu233/kableExtra/pull/743
* https://github.com/haozhu233/kableExtra/pull/751
* https://github.com/haozhu233/kableExtra/issues/534

Issues resolved:

* 1-row table problems https://github.com/vincentarelbundock/kableExtra/commit/3a6b4dba0f5a6467b4f447bb0c892dc29c2527d9
  - https://github.com/haozhu233/kableExtra/issues/658
  - https://github.com/haozhu233/kableExtra/issues/613
* https://github.com/haozhu233/kableExtra/issues/689  https://github.com/vincentarelbundock/kableExtra/commit/1a677efb9c9cfc6e1c15a402fb0c6eb1b15d3e91
* https://github.com/haozhu233/kableExtra/issues/748 https://github.com/haozhu233/kableExtra/pull/768/commits/51190efacc122f5f1eff56f0219180e5f5efe71f
* https://github.com/haozhu233/kableExtra/issues/759 https://github.com/vincentarelbundock/kableExtra/commit/f94bcbe8ac9bc45eab2be52a31414a637f137700
* https://github.com/haozhu233/kableExtra/issues/600 https://github.com/vincentarelbundock/kableExtra/commit/032a3ba2bae8d21101582b2c5da9391b097967cc
  - https://github.com/haozhu233/kableExtra/issues/592
  - `auto_format` should be `FALSE` by default. Otherwise, `library(kableExtra)` automatically and silently changes a global option that affects the printing options of `knitr::kable()`. This obviously bad practice, and it breaks `skimr` and `modelsummary`. This is a breaking change, but it has raised many issues.
* https://github.com/haozhu233/kableExtra/issues/618 90e8546be0562695caaaff36b437f289f135c582
  - https://github.com/haozhu233/kableExtra/issues/657

These issues are already solved in Github master and should be closed on the issue tracker:

* https://github.com/haozhu233/kableExtra/issues/596
* https://github.com/haozhu233/kableExtra/issues/624

Help issues with existing solutions (not bug reports; not feature requests). Can probably be closed:

* https://github.com/haozhu233/kableExtra/issues/661

**Comment by vincentarelbundock** [comment]
Wonderful news! Again, thanks so much for your work on this essential package!

**Comment by vincentarelbundock** [comment]
That sounds great. Yes, I agree this is a problem with no perfect solution. Let me know if I can help with anything (but I probably won't have time for 2-3 weeks).

**Comment by haozhu233** [comment]
Parser added. Now a markdown table will be parsed back to dataframe and rerun with the `kbl` function to generate either html/latex. 

Now the only major thing that won't work is the table labels and the latex booktabs/longtable options in this case. We lost these information in this process. Let me check with @yihui and see if he can pass down these information as some kind of metadata in markdown kable.

**Comment by dmurdoch** [comment]
I think #534 is still an issue.  I'm checking the PR #646 now...

**Comment by dmurdoch** [comment]
Sorry, false alarm in the previous comment, now deleted.

**Pull request merged**
