### PR TITLE
fix #522, spec_line glitches and improvements

### LINKED ISSUE #522: fix glitches in spec_line
My first PR with `spec_line` included some bugs, this issue is meant to document them:

- `xlim`/`ylim` expansion is calculated incorrectly
- `border` is not a graphic parameter in `plot.default`
- dots are not always shown well or completely, depending on the expansion/dot-size, exacerbated by the expansion problem
- parameters are global for the column, it is better to allow per-plot variation (feature, not technically a bug)

Expansion bug:

```r
mpg_list <- split(mtcars$mpg, mtcars$cyl)
inline_plot <- data.frame(cyl = c(4, 6, 8), wrong = "", expected = "")
inline_plot %>% 
  kbl(booktabs = T) %>%
  kable_paper(full_width = F) %>%
  column_spec(2, image = spec_line(lapply(mpg_list, `+`, 1000), same_lim = FALSE)) %>%
  column_spec(3, image = spec_line(mpg_list, same_lim = FALSE))
```

image

Options per list item:

```r
mpg_list <- split(mtcars$mpg, mtcars$cyl)
inline_plot <- data.frame(cyl = c(4, 6, 8), wrong = "", expected = "")
inline_plot %>% 
  kbl(booktabs = T) %>%
  kable_paper(full_width = F) %>%
  column_spec(2, image = spec_line(mpg_list, col = c("green4", "red", "blue"), same_lim = FALSE)) %>%
  column_spec(3, image = spec_line(mpg_list, col = c("green4", "red", "blue"), same_lim = FALSE))
```

image

(image photoshopped to get expected in there)

### PR DESCRIPTION
**Pull request by r2evans**
- xlim/ylim expansion was incorrect
- remove border= from plot parameters (carryover from spec_hist)
- fix how min/max dots are sometimes truncated (using xpd)
- allow most parameters to be per-plot instead of all-plots global

### CODE REVIEW

**Comment by r2evans** [comment]
Hey @haozhu233, question for you ...

As I'm working with this, I just played with an suggest we an argument `type="l"` to this function. This allows one to change from lines to points with just `type="p"` (scatter plot or non-contiguous data points), `type="h"` (histogram like vertical lines, quasi-polygon), etc. As I play with this, it seems much more meaningful to name this function `spec_plot`, since it's really just `plot` repackaged within the `spec_` namespace.

For my other function (PR tbd), that would change my `spec_plot` (which accepts an arbitrary function for plotting) to something like `spec_plotfunc` or `spec_func`.

Looking for your guidance (or approval) here, since it's your package: does it make sense to you to rename this from `spec_line` to `spec_plot`?

**Comment by r2evans** [comment]
Progess:

```lang-r
mtcars_list <- mtcars %>%
  group_by(cyl) %>%
  summarize(mpg = list(mpg), disp = list(disp))
transmute(mtcars_list, cyl, lines = "", points = "", scatter = "", polys = "") %>%
  kbl(booktabs = TRUE) %>%
  kable_paper(full_width = FALSE) %>%
  column_spec(2, image = spec_line(mtcars_list$mpg)) %>%
  column_spec(3, image = spec_line(mtcars_list$mpg, type = "p")) %>%
  column_spec(4, image = spec_line(mtcars_list$mpg, mtcars_list$disp,
                                   cex = 0.5, pch = 16, type = "p")) %>%
  column_spec(5, image = spec_line(mtcars_list$mpg, polymin = 7))
```

image

**Comment by haozhu233** [comment]
@r2evans Sure, I totally agree with you on this part and the new plots you introduced are so pretty! From the user's perspective, if they are familiar with r's base plot, this will feel very natural to them! This is definitely a great improvement!

**Review by haozhu233 — APPROVED** [review]

**Comment by haozhu233** [comment]
@r2evans just reviewed all the changes so far and I think it's ready to go. Thanks again for all the contributions and for the improvements you made for these spec_plot functions. Do you want to be added as an author of this package?

**Comment by r2evans** [comment]
I'll change the function name and run a few more tests before submitting ... thanks.

**Comment by r2evans** [comment]
@haozhu233, I think I'm done with this set of edits. Per your question to me, I added myself as a `ctb` in `DESCRIPTION`.

I think the updated vignettes (I took the liberty) demonstrate its versatility:

image

Feel free to comment, suggest, or merge at will :-) 

(Next PR will likely add pdf and generic devices (in #524), then `spec_plotfun` (#503), and all the while I'll be playing with #507, as I think that can be a game-changer (for me at least).)

**Comment by haozhu233** [comment]
Awesome! Thanks!

**Pull request merged**
