### PR TITLE
Fix output type detection in .onLoad

### LINKED ISSUE #750: Errors in Bookdown after updating R 4.3.0
**Describe the bug**
Failed to load the pkg in book down environment
the error message is as below

Error: package or namespace load failed for 'kableExtra':
 .onLoad failed in loadNamespace() for 'kableExtra', details:
  call: !is.null(rmarkdown::metadata$output) && rmarkdown::metadata$output %in% 
  error: 'length = 2' in coercion to 'logical(1)'

**To Reproduce**
1. Create a bookdown project
2. Call `library(kableExtra)` in a Rmd file
3. Build the project

it's too simple to reproduce.
when I rolled back R to 4.2.3 and the error was gone.

### PR DESCRIPTION
**Pull request by kupietz**
Fixes R 4.3 compatibility and resolves #750

### CODE REVIEW

**Comment by oldiya** [comment]
Hi, is this working? and if yes, is it possible to install this branch?

**Comment by kupietz** [comment]
> Hi, is this working? and if yes, is it possible to install this branch?

Yes, it's working with R 4.2 and 4.3 and probably older versions. I also I think it is the proper solution. You can install my patched version, e.g. with:
```
devtools::install_github("kupietz/kableExtra")
```

**Comment by oldiya** [comment]
the patched version works for me, thanks!!

**Comment by kjewell** [comment]
and for me.

**Comment by JohannPopp** [comment]
Thank you Kupietz. It works fine for me too.

After right installation the Rmd-file was rendered without problems but loading the package interactively throw an error (forgot to note it). But this was gone after a reboot. Now it is working fine in both modes.

Kind regards 
Johann

**Comment by yjpiano** [comment]
> > Hi, is this working? and if yes, is it possible to install this branch?
> 
> Yes, it's working with R 4.2 and 4.3 and probably older versions. I also I think it is the proper solution. You can install my patched version, e.g. with:
> 
> ```
> devtools::install_github("kupietz/kableExtra")
> ```

Thank you, @kupietz!

**Comment by haozhu233** [comment]
Thank you @kupietz for this PR! This change was manually merged in #768.

**Comment by bshor** [comment]
I am using [Fedora COPR R archive](https://copr.fedorainfracloud.org/coprs/iucar/cran/). I have to install the Github version because the COPR version is still 1.3.4.

**Comment by vincentarelbundock** [comment]
Yes, the fixed version is not yet on CRAN, and I imagine it will take some time after that before it is available on the various linux distribution repositories.

**Pull request closed without merging**
